[package]
name = "yamlpath"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7", optional = true }
thiserror = "1.0.63"
tree-sitter = "0.23.0"
tree-sitter-yaml = "0.6.1"

[features]
default = ["parse"]
parse = ["dep:nom"]
