[package]
name = "yamlpath"
version = "0.12.0"
description = "Format-preserving YAML feature extraction"
authors = ["William Woodruff <william@yossarian.net>"]
repository = "https://github.com/woodruffw/yamlpath"
readme = "../README.md"
keywords = ["yaml"]
edition = "2021"
license = "MIT"

[dependencies]
thiserror = "1.0.63"
tree-sitter = "0.23.0"
tree-sitter-yaml = "0.6.1"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
