[package]
name = "yp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
nom = "8"
yamlpath = { version = "*", path = "../yamlpath" }
