[package]
name = "yp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
nom = "7"
yamlpath = { version = "*", path = "../yamlpath" }
